### ISSUE TITLE
Step Outputs : option to expand/show the full description

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#1]
Right now the editor shows only the first line of the Step Output's `description` property, which can lead to missing important informations.

Copy from the original issue (https://github.com/bitrise-io/bitrise.io/issues/61):

From the same step is how a very important comment about when the `BITRISE_XAMARIN_TEST_TO_RUN_ID` output is set isn't rendered.

``` yaml
  - BITRISE_XAMARIN_TEST_TO_RUN_ID:
    opts:
      title: Test to run ID.
      description: |
        Test to run ID.

        This output is available only if 'test_cloud_is_async' is set to 'yes'.
```

![image](https://cloud.githubusercontent.com/assets/382420/18161396/144658ae-7032-11e6-84da-6df942f0bfd2.png)
