### ISSUE TITLE
[!] Android Keystore: save metadata does not save metadata

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#113]
1. Upload a keystore
1. Specify the metadata / passwords
1. Click Save Metadata
1. then reload the page

Metadata are gone :/

**Comment by viktorbenei** [comment]
Workaround: specify those as Env Vars, on the Env Vars tab. You can see which input would be assigned to which env var on the keystore's UI

![screenshot from 2017-05-13 08-31-20](https://cloud.githubusercontent.com/assets/430618/26023188/f4579af6-37b6-11e7-9a99-bd4882eea3d0.png)

- Keystore password: `$BITRISEIO_ANDROID_KEYSTORE_PASSWORD`
- Keystore alias: `$BITRISEIO_ANDROID_KEYSTORE_ALIAS`
- Private key password: `$BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD`

Define these in either Env Vars or in Secrets (depending on whether you need these in pull request builds or not)

![screenshot from 2017-05-13 08-33-28](https://cloud.githubusercontent.com/assets/430618/26023187/ebdf6066-37b6-11e7-8cd0-5d77ae109a05.png)

Or if you're more of a bitrise.yml guy or gal:

```
app:
  envs:
  - BITRISEIO_ANDROID_KEYSTORE_PASSWORD: 
  - BITRISEIO_ANDROID_KEYSTORE_ALIAS: 
  - BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: 
```
