### ISSUE TITLE
Stale output variables section for steps outside steplib

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#122]
Steps to reproduce:
- click on step having `git::` step source - output variables section is empty
- click on step declaring output variable - output variables section contains it
- click on first step again - output variables section still contains previous values

Sample workflow which reproduces this issue:
```yaml
  test:
    steps:
    - git::https://github.com/DroidsOnRoids/steps-create-android-emulator.git@abi:
        inputs:
        - name: test
        - options: 
        - tag: default
        - platform: android-24
    - activate-ssh-key@3.1.1: {}
```
