### ISSUE TITLE
Invalid step ID (?) + switching to another tab then back to Workflow : failed to load workflow

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#186]
Using the config below the workflow loads the first time, but switching to another tab then back to Workflow you get **failed to load workflow**

**NOTE:** the custom `git` step's ref is wrong, it's `git:` instead of `git::`, but the workflow still loads the first time and not after that

```
---
format_version: '4'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios
trigger_map:
- push_branch: "*"
  workflow: primary
- pull_request_source_branch: "*"
  workflow: primary
workflows:
  deploy:
    steps:
    - activate-ssh-key@3.1.1:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@3.5.1: {}
    - cache-pull@1.0.0: {}
    - script@1.1.4:
        title: Do anything with Script step
    - git:https://github.com/tib/steps-certificate-and-profile-installer@master: 
    - xcode-test@1.18.7:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
    - xcode-archive@2.1.0:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
    - deploy-to-bitrise-io@1.3.6: {}
    - cache-push@1.1.4: {}
  primary:
    steps:
    - activate-ssh-key@3.1.1:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@3.5.1: {}
    - cache-pull@1.0.0: {}
    - script@1.1.4:
        title: Do anything with Script step
    - git:https://github.com/tib/steps-certificate-and-profile-installer@master: 
    - xcode-test@1.18.7:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
    - deploy-to-bitrise-io@1.3.6: {}
    - cache-push@1.1.4: {}
app:
  envs:
  - opts:
      is_expand: false
    BITRISE_PROJECT_PATH: ios-simple-objc/ios-simple-objc.xcodeproj
  - opts:
      is_expand: false
    BITRISE_SCHEME: ios-simple-objc

```
