### ISSUE TITLE
Please make sure that bitrise.yml tab can load even if the bitrise.yml is not correct!

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#272]
E.g. try to load this bitrise.yml (invalid trigger map - hash instead of array):

```
format_version: "5"
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: other
trigger_map: {}
workflows:
  primary:
    steps:
    - activate-ssh-key@3.1.1:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@4.0.5: {}
    - script@1.1.5:
        title: Do anything with Script step
    - deploy-to-bitrise-io@1.3.10: {}
```

The editor will give an error and that's OK

<img width="1227" alt="screen shot 2018-03-15 at 10 58 11" src="https://user-images.githubusercontent.com/430618/37456498-d8fac84e-283f-11e8-8134-ed5c7e413710.png">

but will not allow loading it in bitrise.yml mode / tab!!

<img width="1205" alt="screen shot 2018-03-15 at 10 59 12" src="https://user-images.githubusercontent.com/430618/37456526-ed12938e-283f-11e8-9c2e-822b8f5a80fe.png">
