### ISSUE TITLE
Local workflow editor not displaying valid bitrise.yml file

### ISSUE THREAD

**Issue by asos-chrisblackmore** [bitrise-io/bitrise-workflow-editor#358]
When creating a new workflow on `bitrise.io` from an empty template, the following (word for word, space for space) is added to `bitrise.yml`:

```
  workflow-test:
    steps:
    - script@1.1.5: {}
    meta:
      bitrise.io:
        stack: osx-xcode-10.1.x
```

Notice that this includes a workflow specific stack (`osx-xcode-10.1.x`) which was selected from the dropdown available under the _Stack_ tab on bitrise.io.

However, when attempting to use this `bitrise.yml` file with the local workflow editor I am presented with an empty editor - _Workflow_ and _Triggers_ tabs are empty:

<img width="1319" alt="screenshot 2019-02-04 at 16 21 08" src="https://user-images.githubusercontent.com/13540269/52221377-f4e06f00-2898-11e9-816c-abcd948b2d51.png">

In Terminal I receive the following:

```
Exception: RespondWith: Error: json: unsupported type: map[interface {}]interface {}
 => GET: /api/bitrise-yml.json - 18.434831ms ()
 => POST: /api/connection - 526ns ()
```

 However, making a small change to the workflow in the local `bitrise.yml` file - namely aligning `stack` with `bitrise.io` under `meta`, everything seems to work:

```
  workflow-test:
    steps:
    - script@1.1.5:
        inputs:
        - content: '# ruby ./path/to/script.rb'
    meta:
      bitrise.io:
      stack: osx-xcode-10.1.x
```
<img width="1292" alt="screenshot 2019-02-04 at 16 24 16" src="https://user-images.githubusercontent.com/13540269/52221566-56a0d900-2899-11e9-9245-7eb1004defa7.png">

I'm not entirely sure if this is an issue with the workflow editor, or that when selecting a workflow specific stack inserts incorrect information into the `yml` file on `bitrise.io`.

Here's the full `bitrise.yml` that I'm working with:

```
format_version: "4"
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios
trigger_map:
- push_branch: develop
  workflow: workflow-test
workflows:
  workflow-test:
    steps:
    - script@1.1.5:
        inputs:
        - content: '# ruby ./path/to/script.rb'
    meta:
      bitrise.io:
        stack: osx-xcode-10.1.x
```
