### ISSUE TITLE
[!!!] Save does not save inputs of steps for a brand new workflow

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#63]
Reproduction:

1. Create new workflow, using "empty" as the option
1. Add a Script step
1. Change the script content
1. Click "Save"
1. Reload

The script content was not saved :/

**Comment by viktorbenei** [comment]
Actually this happens without creating a new workflow!!

Just add a new step, don't save, change an input of the step and then save -> the input change will not be saved!!

**Comment by viktorbenei** [comment]
Still happens, using the original reproduction steps, just clone another workflow.

**Comment by viktorbenei** [comment]
Repro:

```
format_version: 1.3.1
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
trigger_map:
- push_branch: '*'
  workflow: beta
- pull_request_source_branch: '*'
  workflow: beta
- tag: '*'
  workflow: release
workflows:
  beta:
    steps:
    - gradle-runner@1.5.4:
        inputs:
        - gradle_task: assembleOne
  release:
    steps:
    - gradle-runner@1.5.4:
        inputs:
        - gradle_task: assembleTwo
```

1. Load this
1. Add a new workflow, clone any of the other ones
1. Select the Gradle step in the new workflow
1. Change the task input to anything, e.g. "assembleASDF"
1. Save -> the task is not saved, the step is saved with a default input
