### ISSUE TITLE
Empty step issue

### ISSUE THREAD

**Issue by erosdome** [bitrise-io/bitrise-workflow-editor#75]
If an app config YML has empty steps listed only by ID, like:

```
 steps:
    - activate-ssh-key: 
    - git-clone: 
    - certificate-and-profile-installer: 
```

The workflows tab in this case will raise an error when trying to parse the YML.
