### ISSUE TITLE
UI stuck at "insert variable"

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#83]
- Added a Workflow env var for the primary workflow
- then switched back to the workflow editor
- clicked into a script step
- clicked "Insert variable"
- an empty popup came up, and I could not close it any way, the UI hang/got stuck

![screenshot from 2017-04-26 14-42-57](https://cloud.githubusercontent.com/assets/430618/25435178/7cced3ac-2a8f-11e7-87df-a30f70051a66.png)

---

Error in the Console:

```
main.js:25132 TypeError: Cannot read property 'envs' of undefined
    at loadInsertableVariables (main.js:57520)
    at Popup.viewModel.popup.beforeAppearCallback (main.js:57414)
    at main.js:55418
    at Scope.$digest (main.js:28560)
    at ChildScope.$apply (main.js:28824)
    at HTMLButtonElement.<anonymous> (main.js:36447)
    at HTMLButtonElement.dispatch (main.js:4666)
    at HTMLButtonElement.elemData.handle (main.js:4334)
(anonymous)	@	main.js:25132

```

**Comment by viktorbenei** [comment]
Reloading the editor solved the issue, and after the reload it could properly present the Insert Variable popup too.

I think the issue might be that:

- I started from the Workflows tab
- Then went to Env Vars tab, and did set the workflow specific env var
- Then went back to the Workflows tab, most likely without "Save", just switched between the tabs
- And then clicked Insert Variable

**Comment by viktorbenei** [comment]
For ref. the `bitrise.yml`:

```
format_version: 1.3.1
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
trigger_map:
- push_branch: '*'
  workflow: primary
- pull_request_source_branch: '*'
  workflow: primary
workflows:
  primary:
    envs:
    - CACHED_DEPLOY_INFO_FILE_PATH: $BITRISE_CACHE_DIR/last_release_build_number
    steps:
    - activate-ssh-key@3.1.1:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@3.4.1: {}
    - cache-pull@0.9.2: {}
    - script@1.1.3:
        title: Read from Cache
    - script@1.1.3:
        title: Write into Cache
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            echo "$BITRISE_BUILD_NUMBER" > ""
    - cache-push@0.9.4: {}
```
